# Generated by Django 2.2.7 on 2019-11-29 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('product_desc', models.CharField(max_length=500)),
                ('product_brand', models.CharField(max_length=20)),
                ('product_price', models.FloatField()),
                ('product_status', models.CharField(max_length=10)),
                ('product_image', models.CharField(max_length=500)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Products',
            },
        ),
    ]
