# Generated by Django 3.0 on 2019-12-07 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poke_id', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=50)),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('image', models.CharField(max_length=500)),
                ('held_items', models.CharField(max_length=500)),
                ('abilities', models.CharField(max_length=500)),
                ('types', models.CharField(max_length=500)),
                ('stats', models.CharField(max_length=500)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Pokemon',
            },
        ),
    ]
