# Generated by Django 3.0 on 2020-01-14 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokepolls', '0003_auto_20191214_1515'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abilities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Abilities',
            },
        ),
        migrations.CreateModel(
            name='HeldItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'HeldItems',
            },
        ),
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Types',
            },
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='abilities',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='evolution',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='held_items',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='stats',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='types',
        ),
        migrations.CreateModel(
            name='PokeTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokepolls.Pokemon')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokepolls.Types')),
            ],
        ),
        migrations.CreateModel(
            name='PokeStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_type', models.CharField(choices=[('b', 'base-stat'), ('e', 'effort')], max_length=1)),
                ('speed', models.FloatField()),
                ('special_defence', models.FloatField()),
                ('special_attack', models.FloatField()),
                ('defence', models.FloatField()),
                ('attack', models.FloatField()),
                ('hp', models.FloatField()),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokepolls.Pokemon')),
            ],
            options={
                'verbose_name_plural': 'PokeStats',
            },
        ),
        migrations.CreateModel(
            name='PokeHeldItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('heldItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokepolls.HeldItems')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokepolls.Pokemon')),
            ],
        ),
        migrations.CreateModel(
            name='PokeEvolutions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('order', models.PositiveIntegerField()),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokepolls.Pokemon')),
            ],
        ),
        migrations.CreateModel(
            name='PokeAbilities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('ability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokepolls.Abilities')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokepolls.Pokemon')),
            ],
        ),
    ]
